version: "3.8"

services:
  nginx:
    image: nginx:alpine # 使用轻量的Nginx镜像
    container_name: vite-react-app
    restart: always # 容器退出时自动重启
    ports:
      - "80:80" # 映射主机80端口到容器80端口（可修改为443并添加HTTPS配置）
    volumes:
      - ./dist:/usr/share/nginx/html # 挂载前端静态文件到Nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # 挂载自定义Nginx配置
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"] # 健康检查：访问本地主页
      interval: 30s
      timeout: 10s
      retries: 3
