name: my frist github action workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.12"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cache-node-modules-

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./dist/

      - name: Verify downloaded files
        run: |
          tree ./dist || ls -R ./dist  # 显示目录结构

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p web && cd web
            # 备份旧版本
            if [ -d "dist" ]; then
              mv dist dist_old_$(date +%Y%m%d%H%M%S)
            fi
            # 创建新的 dist 目录
            mkdir -p dist
          src: ./dist/* # 注意：添加了/*以指定dist目录的内容，而不是目录本身
          target: /web/dist/ # 确保目标目录以/结尾，表示上传到该目录内
          # 其他可选参数
          overwrite: true # 覆盖远程已有文件
          debug: true # 调试模式（需要时设为 true，查看详细日志）

      - name: Verify deployment
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "远程服务器文件列表:"
            ls -la /web/dist
            tree ./dist || ls -R ./dist  # 显示目录结构
