name: 使用appleboy/ssh-action@v1.0.2部署文件

on:
  push:
    branches: [main]

jobs:
  deploy-with-appleboy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 创建测试文件
        id: create-file
        run: |
          # 创建本地文件并记录绝对路径
          mkdir -p ${{ github.workspace }}/local
          echo "测试内容 - $(date)" > ${{ github.workspace }}/local/world.txt

          # 验证本地文件
          echo "本地文件信息："
          ls -la ${{ github.workspace }}/local/world.txt
          cat ${{ github.workspace }}/local/world.txt

          # 输出文件路径供后续步骤使用
          echo "file-path=${{ github.workspace }}/local/world.txt" >> $GITHUB_OUTPUT

      - name: 预配置SSH环境
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          debug: true
          script: |
            # 服务器环境检查与准备
            echo "当前登录用户：$(whoami)"

            # 准备目标目录
            mkdir -p /www
            echo "目录初始权限："
            ls -ld /www

            # 授权目录权限
            sudo chown -R $(whoami) /www
            chmod 755 /www
            echo "授权后目录权限："
            ls -ld /www

            # 测试直接写入能力
            echo "测试直接写入："
            if touch /www/test_permission.txt; then
              echo "✅ 直接写入成功"
              rm /www/test_permission.txt
            else
              echo "❌ 直接写入失败"
              exit 1
            fi

            # 检查磁盘空间
            df -h /www

      - name: 使用SCP传输文件
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          debug: true # 显示传输详细日志
          command_timeout: 30s

          # SCP传输核心配置
          src: ${{ steps.create-file.outputs.file-path }} # 本地文件绝对路径
          target: /www/ # 远程目标目录（必须以/结尾）
          overwrite: true
          recursive: false # 单个文件传输

          # 传输后立即验证（同一SSH会话）
          script: |
            echo "传输后立即检查："
            ls -la /www/world.txt || exit 1
            echo "传输后文件内容："
            cat /www/world.txt

      - name: 最终验证（独立会话）
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "最终验证文件存在性："
            if [ -f /www/world.txt ]; then
              echo "✅ 远程文件存在"
              cat /www/world.txt
            else
              echo "❌ 远程文件不存在"
              exit 1
            fi

      - name: 清理工作
        if: always()
        run: |
          echo "部署流程结束"
