name: test upload and deploy

on: [push]

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a file
        run: |
          mkdir -p path/to/artifact
          echo "This is a test file." > path/to/artifact/world.txt
      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact/*
      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: path/to/downloaded
      - name: Verify downloaded file
        run: |
          if [ -f path/to/downloaded/world.txt ]; then
            echo "File downloaded successfully."
          else
            echo "File download failed."
            exit 1
          fi
      - name: deloy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p www && cd www
            # 备份旧版本
            if [ -d "world.txt" ]; then
              mv world.txt world$(date +%Y%m%d%H%M%S).txt
            fi
            echo "Deployment completed successfully."
          src: path/to/downloaded/* # 注意：添加了/*以指定dist目录的内容，而不是目录本身
          target: /www/ # 确保目标目录以/结尾，表示上传到该目录内
          # 其他可选参数
          overwrite: true # 覆盖远程已有文件
          debug: true # 调试模式（需要时设为 true，查看详细日志）
