name: test upload and deploy

on: [push]

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test file
        run: |
          mkdir -p path/to/artifact
          echo "This is a test file." > path/to/artifact/world.txt
          ls -la path/to/artifact/  # 确认文件创建

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact/*
          if-no-files-found: error

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: path/to/downloaded/
          if-no-artifact-found: error

      - name: 验证Runner中文件路径
        run: |
          echo "下载目录结构："
          ls -R path/to/downloaded  # 关键：确认world.txt的位置

      - name: Deploy via SFTP（更可靠）
        uses: wlixcc/SFTP-Deploy-Action@v1.3.3
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          server: ${{ secrets.SERVER_HOST }}
          ssh_private_key: ${{ secrets.SERVER_SSH_KEY }}
          local_path: "path/to/downloaded/*" # 匹配Runner中文件路径
          remote_path: "/www/"
          args: "-v" # 详细日志

      - name: 最终验证远程文件
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "远程/www目录内容："
            ls -la /www
            if [ -f "/www/world.txt" ]; then
              echo "文件存在，内容："
              cat /www/world.txt
            else
              echo "文件不存在"
              exit 1
            fi
