name: SCP 传输示例（appleboy/ssh-action）

on:
  push:
    branches: [main]

jobs:
  scp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 创建测试文件
        run: |
          mkdir -p ./artifact
          echo "SCP 传输测试 $(date)" > ./artifact/world.txt
          ls -la ./artifact  # 验证文件创建

      - name: 上传到 Artifact（可选，多 Job 场景用）
        uses: actions/upload-artifact@v4
        with:
          name: test-file
          path: ./artifact/world.txt

      - name: 下载 Artifact（可选，多 Job 场景用）
        uses: actions/download-artifact@v4
        with:
          name: test-file
          path: ./downloaded

      - name: 验证下载文件
        run: |
          ls -la ./downloaded  # 确保 world.txt 存在
          cat ./downloaded/world.txt

      - name: 通过 SCP 传输到远程服务器
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22

          # SCP 核心配置
          scp: true
          src: "./downloaded/world.txt" # 本地文件路径（Runner 中）
          target: "/www/" # 远程目标目录（以 / 结尾）
          overwrite: true # 覆盖现有文件
          recursive: false # 传输单个文件，无需递归

          # 远程脚本：创建目录 + 备份旧文件
          script: |
            mkdir -p /www
            cd /www
            if [ -f "world.txt" ]; then
              mv world.txt "world_backup_$(date +%Y%m%d%H%M%S).txt"
              echo "已备份旧文件"
            fi
            echo "当前用户: $(whoami)"
            echo "目录权限: $(ls -ld /www)"

      - name: 验证远程文件
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "远程 /www 目录内容："
            ls -la /www
            if [ -f "/www/world.txt" ]; then
              echo "文件内容："
              cat /www/world.txt
            else
              echo "文件不存在"
              exit 1
            fi
