name: 修复远程写入问题

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 创建测试文件
        run: |
          mkdir -p ./local
          echo "测试内容" > ./local/world.txt
          ls -la ./local  # 验证本地文件存在

      - name: 最终部署验证
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "当前用户：$(whoami)"
            ls -ld /www  # 确认权限
          src: "./local/world.txt"
          target: "/www/"
          overwrite: true

      - name: 确认文件存在
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ -f "/www/world.txt" ]; then
              echo "✅ 最终验证：文件写入成功"
              cat /www/world.txt
            else
              echo "❌ 最终验证：文件仍不存在"
              exit 1
            fi
