name: 构建并部署（使用ssh-scp-ssh-pipelines）
on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Node环境
        uses: actions/setup-node@v4
        with:
          node-version: "22.12"
          cache: "npm"

      - name: 安装依赖
        run: npm ci

      - name: 构建项目
        run: npm run build

      - name: 验证构建产物
        run: ls -R ${{ github.workspace }}/dist

      - name: SSH连接+文件传输+远程验证
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          # 步骤1: 执行远程服务器初始化命令
          first_ssh: |
            echo "===== 登录用户信息 ====="
            whoami
            echo "用户家目录: $HOME"

            # 确保目标目录存在并授权
            if [ ! -d "/www" ]; then
              sudo mkdir -p /www
              sudo chown -R $(whoami) /www
            fi
            chmod 755 /www
            echo "===== /www目录权限 ====="
            ls -ld /www
          # 步骤2: 传输文件（本地到远程）
          scp: |
            ${{ github.workspace }}/dist/* => /www/
          # 步骤3: 传输后验证
          last_ssh: |
            echo "===== 传输后文件列表 ====="
            ls -R /www
            if [ -f "/www/index.html" ]; then
              echo "✅ 部署成功：前端入口文件存在"
            else
              echo "❌ 部署失败：未找到index.html"
              exit 1
            fi
        env:
          # 启用详细日志模式（调试用）
          DEBUG: true
